<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>RuleProxy</AssemblyName>
    <RootNamespace>RuleProxy.Native</RootNamespace>
    <ApplicationIcon>..\icon.ico</ApplicationIcon>
    <Version>0.1.0</Version>
    <PublishSingleFile>false</PublishSingleFile>
    <SatelliteResourceLanguages>zh-Hans</SatelliteResourceLanguages>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="..\icon.ico" />
  </ItemGroup>

</Project>
