<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>RuleProxy.Native.Tests</AssemblyName>
    <RootNamespace>RuleProxy.Native.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RuleProxy.Native\RuleProxy.Native.csproj" />
  </ItemGroup>

</Project>
